# Generated by Django 5.0 on 2023-12-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_delete_test_model_alter_tag_slug_alter_todo_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('title',)},
        ),
    ]
