# Generated by Django 5.0 on 2023-12-26 08:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_profile_avatar_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
