# Generated by Django 5.0 on 2023-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='todo_app.tag'),
        ),
    ]
