# Generated by Django 5.0 on 2023-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_alter_todo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(to='todo_app.tag'),
        ),
    ]
